#!/usr/bin/env python

import glob
from astropy.io import fits
from FlatNorm import *
from SAMOSHelpers import *
from BadPix import fixbad

mask = sys.argv[1]

data_path = [os.path.join(mask+'/flat_fielded/',i) for i in os.listdir(mask+'/flat_fielded/') if i[-4:]=='fits']
print("\nPath to input data is %s\n " % ", ".join(data_path))

output_dir = "%s/%s" % (mask,"CR_corrected")
print("Output direcotry is %s\n " % output_dir)

if not os.path.exists(output_dir): os.mkdir(output_dir)

out_files = ["cr"+os.path.basename(i) for i in data_path]

output_path = [output_dir+"/"+i for i in out_files]
print("Files will be placed in ")
print(", ".join(output_path))

print("\nCleaning cosmic rays...")
[fixbad(i,o) for i,o in zip(data_path,output_path)]


