#!/usr/bin/env python

import glob
from astropy.io import fits
from FlatNorm import *
from SAMOSHelpers import *
from Slit_id import *

db = sys.argv[1]
IsItHere(db)
mask = db[:-1]

f = open(db,"r")
lines = [l.strip() for l in f]
f.close()

masterFlat = [j for j,l in enumerate(lines) if "# MasterFlat" in l]
masterFlat = masterFlat[0]

masterFlat = lines[masterFlat+1:][0]
print("Master flat %s located" %masterFlat)

#I will want to import a file with approximate slit top edges to read into get_edges().

get_edges(masterFlat)
