#!/usr/bin/env python

import glob
from astropy.io import fits
from FlatNorm import *
from SAMOSHelpers import *
from Slit_id import *

db = sys.argv[1]
IsItHere(db)
mask = db[:-3]
print(mask)
f = open(db,"r")
lines = [l.strip() for l in f]
f.close()

masterFlat = [j for j,l in enumerate(lines) if "# MasterFlat" in l]
masterFlat = masterFlat[0]

masterFlat = lines[masterFlat+1:][0]
print("Master flat %s located" %masterFlat)

mask_name = os.path.split(masterFlat)[0]
print(mask_name)
#I will want to import a file with approximate slit top edges to read into get_edges().

get_edges(masterFlat,"LDSS3/TConnor/%s_ycoords_c1.txt"%mask_name)
