#!/usr/bin/env python

import glob
from SAMOSHelpers import *
from Overscan import *

db = sys.argv[1]
IsItHere(db)
mask = db[:-3]

f = open(db,"r")
lines = [l.strip() for l in f]
f.close()

jlamp = [j for j,l in enumerate(lines) if "# lamp" in l]
jflat = [j for j,l in enumerate(lines) if "# flat" in l]
jtarg = [j for j,l in enumerate(lines) if "# targ" in l]
if not jlamp or not jflat or not jtarg:
   MuyMalo("Problem with what files are available!")

jlamp = jlamp[0]
jflat = jflat[0]
jtarg = jtarg[0]

inlamps = lines[jlamp+1:jflat]
inflats = lines[jflat+1:jtarg]
intargs = lines[jtarg+1:]

outlamps = ["%s/%s%s" % (mask,mask,os.path.basename(i)[3:]) for i in inlamps]
outflats = ["%s/%s%s" % (mask,mask,os.path.basename(i)[3:]) for i in inflats]
outtargs = ["%s/%s%s" % (mask,mask,os.path.basename(i)[3:]) for i in intargs]

# IF YOU THINK YOU MIGHT SPAWN JOBS IN THE BACKGROUND OR WHATEVER
#infiles = inlamps+inflats+intargs
#outfiles = outlamps+outflats+outtargs
#commands = ["python Overscan.py %s %s" % (i,o) for i,o in zip(infiles,outfiles)]
#list(map(os.system,commands))

# IF YOU LIKE YOUR SCRIPTS TO GO AND DO EVERYTHING
[Overscan(i,o) for i,o in zip(inlamps,outlamps)]
[Overscan(i,o) for i,o in zip(inflats,outflats)]
[Overscan(i,o) for i,o in zip(intargs,outtargs)]


db = open("%s.db"%(mask),"a")
db.write("## Trimmed/Overscan Subtracted\n")
db.write("# OSLamps\n")
[db.write("%s\n"%(olamp)) for olamp in outlamps]
db.write("# OSFlats\n")
[db.write("%s\n"%(oflat)) for oflat in outflats]
db.write("# OSTargs\n")
[db.write("%s\n"%(otarg)) for otarg in outtargs]
db.close()