#! /usr/bin/env python

from InitializeSAMOS import initialize_SAMOS
from OverscanAndTrim import overscan_and_trim
from NormDivFlats import norm_div_flats
from OutlineSlits import outline_slits

#initialize the data reduction by calling initialize_SAMOS

fuel = initialize_SAMOS('2017-11-30','LMask2')

#next update the fuel data structure
#overwrites old data structure entries as new ones are added.
fuel = overscan_and_trim(fuel)

fuel = norm_div_flats(fuel)

fuel = outline_slits(fuel)

#next step is to identify emission lines in the calibration spectra to get a 
#dispersion solution.  Currently needs to be run manually in an ipython environment.

